### ISSUE TITLE
Fix Stasis Aspect Descriptions

### ISSUE THREAD

**Issue by jbccollins** [jbccollins/destiny-loadout-builder#74]
They are currently wrong. I changed how the descriptions were extracted recently to fix Drenger's Lash.

**Comment by nokynokes** [comment]
Dug into the perk definitions for stasis aspects, looks there are always two perk definitions, one for the quest and one for the unlocked aspect:
```json
{
  displayProperties: {
    description: 'Your Glacier, Duskfield, and Coldsnap grenades have enhanced functionalit
      'Duskfield Grenade: Increases slow-field size and creates a small [Stasis] Stasis crystal on impact.\n' +
      '\n' +
      'Coldsnap Grenade: Seeker creates a [Stasis] Stasis crystal on detonation and chains 
one additional time.',
    name: 'Touch of Winter',
    icon: '/common/destiny2_content/icons/b782f03e26e41a50d08aff335c86feb3.png',
    hasIcon: true
  },
  isDisplayable: true,
  damageType: 0,
  hash: 181665053,
  index: 2341,
  redacted: false,
  blacklisted: false
}
{
  displayProperties: {
    description: 'ASPECT OF INTERFERENCE\n' +
      'Unlock this Stasis Aspect by completing the quests "Aspect of Influence" and "Aspect of Interference," acquired from the Exo Stranger on Europa.',
    name: 'UNLOCKED BY QUEST',
    icon: '/common/destiny2_content/icons/3e93a6de630443a79cf4d4d1942f5a1b.jpg',
    hasIcon: true
  },
  isDisplayable: true,
  damageType: 0,
  hash: 1784140514,
  index: 2151,
  redacted: false,
  blacklisted: false
}
```

I think when we build the descriptions in `utils.ts` we can probably jsut have an extra condition to check `name !== 'UNLOCKED BY QUEST`

**Comment by jbccollins** [comment]
> Dug into the perk definitions for stasis aspects, looks there are always two perk definitions, one for the quest and one for the unlocked aspect:
> 
> ```
> {
>   displayProperties: {
>     description: 'Your Glacier, Duskfield, and Coldsnap grenades have enhanced functionalit
>       'Duskfield Grenade: Increases slow-field size and creates a small [Stasis] Stasis crystal on impact.\n' +
>       '\n' +
>       'Coldsnap Grenade: Seeker creates a [Stasis] Stasis crystal on detonation and chains 
> one additional time.',
>     name: 'Touch of Winter',
>     icon: '/common/destiny2_content/icons/b782f03e26e41a50d08aff335c86feb3.png',
>     hasIcon: true
>   },
>   isDisplayable: true,
>   damageType: 0,
>   hash: 181665053,
>   index: 2341,
>   redacted: false,
>   blacklisted: false
> }
> {
>   displayProperties: {
>     description: 'ASPECT OF INTERFERENCE\n' +
>       'Unlock this Stasis Aspect by completing the quests "Aspect of Influence" and "Aspect of Interference," acquired from the Exo Stranger on Europa.',
>     name: 'UNLOCKED BY QUEST',
>     icon: '/common/destiny2_content/icons/3e93a6de630443a79cf4d4d1942f5a1b.jpg',
>     hasIcon: true
>   },
>   isDisplayable: true,
>   damageType: 0,
>   hash: 1784140514,
>   index: 2151,
>   redacted: false,
>   blacklisted: false
> }
> ```
> 
> I think when we build the descriptions in `utils.ts` we can probably jsut have an extra condition to check `name !== 'UNLOCKED BY QUEST`

Yeah. I actually have a fix for this on a local feature branch. But if you get to push it before me then go for it.

**Comment by jbccollins** [comment]
To fix this you'll need to run `npm run generate` after fixing the logic that filters for that string @nokynokes. That definitions file should not be modified manually.

**Comment by jbccollins** [comment]
I have fixed this
